repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^python/
      - id: ruff-format
        files: ^python/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^python/

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --manifest-path rust/Cargo.toml
        language: system
        files: ^rust/.*\.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --manifest-path rust/Cargo.toml -- -D warnings
        language: system
        files: ^rust/.*\.rs$
        pass_filenames: false
